#!/bin/bash

# Get system information
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p)

# Get hardware information
CPU=$(lshw -class processor | grep -m1 "product" | awk '{print $2, $3, $4}')
CPU_SPEED=$(lscpu | grep "CPU MHz:" | awk '{print $3}')
MAX_CPU_SPEED=$(lscpu | grep "CPU max MHz:" | awk '{print $4}')
RAM=$(free -h | grep "Mem:" | awk '{print $2}')
DISKS=$(lsblk -o NAME,ROTA,SIZE | grep -vE "^NAME" | awk '{print $1, $2, $3}')
VIDEO=$(lshw -class display | grep "product" | awk '{print $2, $3, $4}')

# Get network information
FQDN=$(hostname -f)
HOST_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')
INTERFACE_NAME=$(ip -o -4 route show to default | awk '{print $5}')
IP_ADDRESS=$(ip a show dev $INTERFACE_NAME | grep "inet " | awk '{print $2}')

# Get system status
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ', ')
DISK_SPACE=$(df -h | grep "^/dev/" | awk '{print $6, $4}')
PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1, $2, $3}')
MEMORY_ALLOCATION=$(free -h | grep "Mem:" | awk '{print $3 "/" $2 " (" $7 " free)"}')
LISTENING_PORTS=$(ss -tuln | grep -E "^tcp|^udp" | awk '{print $5}' | cut -d ':' -f2 | sort -n | uniq | tr '\n' ', ')
UFW_RULES=$(sudo ufw status numbered)

# Print system report
echo "
System Report generated by $USER, $(date)

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED / $MAX_CPU_SPEED MHz
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS_SERVER
InterfaceName: $INTERFACE_NAME
IP Address: $IP_ADDRESS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY_ALLOCATION
Listening Network Ports: $LISTENING_PORTS
UFW Rules: $UFW_RULES
"
